const jobs = [
  { id: 1, company: '한화솔루션', title: '품질관리(QC) 신입', role: '품질관리', industry: '화학·소재', type: '신입 정규직', location: '대전·충청권', duties: ['시험·분석', '품질 데이터 관리'], experience: ['신입 가능'], major: '화학·공학 계열', size: '대기업·중견기업', preferences: ['분석 장비 경험', '품질 관련 자격증'], deadline: 6, logo: 'H', color: '#173b72', saved: false },
  { id: 2, company: 'LG화학', title: '배터리 소재 품질관리 인턴', role: '품질관리', industry: '화학·소재', type: '인턴', location: '수도권', duties: ['시험·분석', '품질 데이터 관리'], experience: ['경력 무관'], major: '화학·공학 계열', size: '대기업·중견기업', preferences: ['분석 장비 경험'], deadline: 9, logo: 'L', color: '#c72e3d', saved: true },
  { id: 3, company: '셀트리온', title: '바이오 품질관리(QA) 인턴', role: '품질관리', industry: '제약·바이오', type: '인턴', location: '수도권', duties: ['품질 데이터 관리'], experience: ['경력 무관'], major: '화학·공학 계열', size: '대기업·중견기업', preferences: ['품질 관련 자격증'], deadline: 12, logo: 'C', color: '#1769a5', saved: false },
  { id: 4, company: '에코프로비엠', title: '소재 품질분석 인턴', role: '품질관리', industry: '화학·소재', type: '인턴', location: '대전·충청권', duties: ['시험·분석'], experience: ['신입 가능'], major: '화학·공학 계열', size: '중소기업·스타트업', preferences: ['분석 장비 경험'], deadline: 15, logo: 'E', color: '#39a67d', saved: false },
  { id: 5, company: 'GC녹십자', title: '품질보증(QA) 신입', role: '품질관리', industry: '제약·바이오', type: '신입 정규직', location: '수도권', duties: ['품질 데이터 관리'], experience: ['신입 가능'], major: '화학·공학 계열', size: '대기업·중견기업', preferences: [], deadline: 18, logo: 'G', color: '#2c8d8a', saved: false },
  { id: 6, company: '동진쎄미켐', title: '반도체 소재 품질관리 신입', role: '품질관리', industry: '화학·소재', type: '신입 정규직', location: '수도권', duties: ['시험·분석', '품질 데이터 관리'], experience: ['신입 가능'], major: '화학·공학 계열', size: '대기업·중견기업', preferences: ['분석 장비 경험', '품질 관련 자격증'], deadline: 21, logo: 'D', color: '#5d58b7', saved: false },
  { id: 7, company: '바이오니아', title: '분자진단 품질관리 인턴', role: '품질관리', industry: '제약·바이오', type: '인턴', location: '대전·충청권', duties: ['시험·분석'], experience: ['경력 무관'], major: '화학·공학 계열', size: '중소기업·스타트업', preferences: ['분석 장비 경험'], deadline: 24, logo: 'B', color: '#e07845', saved: false },
  { id: 8, company: '코스맥스', title: '화장품 품질관리 인턴', role: '품질관리', industry: '화학·소재', type: '인턴', location: '수도권', duties: ['품질 데이터 관리'], experience: ['경력 무관'], major: '화학·공학 계열', size: '대기업·중견기업', preferences: [], deadline: 28, logo: 'K', color: '#d65f95', saved: false }
];
let appliedFilters = { role: '', industry: '', type: '', location: '', duty: '', experience: '', major: '', size: '', preferences: false };
let selectedJob = null;
const $ = selector => document.querySelector(selector);
function getFormFilters() { return { role: $('#roleFilter').value, industry: $('#industryFilter').value, type: $('#typeFilter').value, location: $('#locationFilter').value, duty: $('#dutyFilter').value, experience: $('#experienceFilter').value, major: $('#majorFilter').value, size: $('#sizeFilter').value, preferences: $('#preferenceFilter').checked }; }
function matches(job, filters) { return (!filters.role || job.role === filters.role) && (!filters.industry || job.industry === filters.industry) && (!filters.type || job.type === filters.type) && (!filters.location || job.location === filters.location) && (!filters.duty || job.duties.includes(filters.duty)) && (!filters.experience || job.experience.includes(filters.experience)) && (!filters.major || job.major === filters.major) && (!filters.size || job.size === filters.size) && (!filters.preferences || job.preferences.length > 0); }
function score(job) { let total = 0; if (job.role === '품질관리' && ['화학·소재', '제약·바이오'].includes(job.industry)) total += 3; if (['대전·충청권', '수도권'].includes(job.location) && ['인턴', '신입 정규직'].includes(job.type)) total += 3; if (job.major === '화학·공학 계열' && (job.experience.includes('신입 가능') || job.experience.includes('경력 무관')) && job.duties.some(duty => ['시험·분석', '품질 데이터 관리'].includes(duty))) total += 3; return total; }
function render() { const visible = jobs.filter(job => matches(job, appliedFilters)).sort((a, b) => $('#sortFilter').value === 'deadline' ? a.deadline - b.deadline : score(b) - score(a) || a.deadline - b.deadline); $('#resultCount').textContent = visible.length; $('#navCount').textContent = visible.length; $('#savedCount').textContent = jobs.filter(job => job.saved).length; $('#jobGrid').innerHTML = visible.map(job => `<article class="job-card ${score(job) === 9 ? 'recommended' : ''}" data-job-id="${job.id}" tabindex="0"><div class="card-top"><div class="company-logo" style="background:${job.color}">${job.logo}</div><div class="card-badges">${score(job) === 9 ? '<span class="recommend-badge">추천</span>' : ''}<button class="bookmark ${job.saved ? 'saved' : ''}" data-save-id="${job.id}" aria-label="공고 저장">${job.saved ? '♥' : '♡'}</button></div></div><p class="company">${job.company}</p><h3>${job.title}</h3><div class="card-meta"><span>⌖ ${job.location}</span><span>${job.type}</span></div><div class="tags">${job.duties.map(duty => `<span class="tag">${duty}</span>`).join('')} ${job.preferences.length ? '<span class="tag preference">우대 조건 있음</span>' : ''}</div><div class="card-footer"><span>지원 마감 <strong>D-${job.deadline}</strong></span><span>매칭 <strong>${score(job) * 10 + 5}%</strong></span></div></article>`).join(''); $('#emptyState').hidden = visible.length > 0; const labels = Object.entries(appliedFilters).filter(([, value]) => value).map(([key, value]) => key === 'preferences' ? '우대 조건 있음' : value); $('#activeQuery').innerHTML = labels.length ? `<span>적용 중</span>${labels.map(label => `<b>${label}</b>`).join('')}` : ''; $('#activeQuery').hidden = labels.length === 0; document.querySelectorAll('.job-card').forEach(card => { card.addEventListener('click', () => openDetail(Number(card.dataset.jobId))); card.addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openDetail(Number(card.dataset.jobId)); } }); }); document.querySelectorAll('[data-save-id]').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); toggleSave(Number(button.dataset.saveId)); })); }
function applyFilters() { appliedFilters = getFormFilters(); render(); toast('선택한 조건을 적용했어요.'); }
function resetFilters() { document.querySelectorAll('select').forEach(select => { if (select.id !== 'sortFilter') select.value = ''; }); $('#preferenceFilter').checked = false; appliedFilters = getFormFilters(); render(); toast('필터를 초기화했어요.'); }
function toggleSave(id) { const job = jobs.find(item => item.id === id); job.saved = !job.saved; render(); toast(job.saved ? '저장한 공고에 추가했어요.' : '저장한 공고에서 삭제했어요.'); if (selectedJob?.id === id) $('#modalSave').textContent = job.saved ? '♥ 저장됨' : '♡ 저장'; }
function openDetail(id) { selectedJob = jobs.find(job => job.id === id); $('#modalCompany').textContent = selectedJob.company; $('#modalMatch').textContent = `추천 점수 ${score(selectedJob)}/9`; $('#modalTitle').textContent = selectedJob.title; $('#modalMeta').textContent = `${selectedJob.location} · ${selectedJob.type} · 지원 마감 D-${selectedJob.deadline}`; $('#modalTags').innerHTML = [selectedJob.industry, selectedJob.size, ...selectedJob.duties].map(tag => `<span class="tag">${tag}</span>`).join(''); $('#modalDuty').textContent = selectedJob.duties.join(' · '); $('#modalQualification').textContent = `${selectedJob.major} 지원 가능 · ${selectedJob.experience.join(' 또는 ')}`; $('#modalSave').textContent = selectedJob.saved ? '♥ 저장됨' : '♡ 저장'; $('#detailModal').hidden = false; document.body.classList.add('modal-open'); }
function closeDetail() { $('#detailModal').hidden = true; document.body.classList.remove('modal-open'); selectedJob = null; }
function toast(message) { $('#toast').textContent = message; $('#toast').classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => $('#toast').classList.remove('show'), 1800); }
$('#applyButton').addEventListener('click', applyFilters); $('#resetButton').addEventListener('click', resetFilters); $('#sortFilter').addEventListener('change', render); $('#modalClose').addEventListener('click', closeDetail); $('#detailModal').addEventListener('click', event => { if (event.target.id === 'detailModal') closeDetail(); }); $('#modalSave').addEventListener('click', () => { if (selectedJob) toggleSave(selectedJob.id); }); $('#modalApply').addEventListener('click', () => toast('지원 페이지 URL (모름)')); document.addEventListener('keydown', event => { if (event.key === 'Escape' && selectedJob) closeDetail(); });
render();
