let jobs = [];
let appliedFilters = { role: '', industry: '', type: '', location: '', duty: '', experience: '', major: '', size: '', preferences: false };
let selectedJob = null;
const $ = selector => document.querySelector(selector);
const youthInternCodes = ['R1050', 'R1060', 'R1070'];
function empty(value) { return value == null ? '' : String(value); }
function splitList(value) { return empty(value).split(',').map(item => item.trim()).filter(Boolean); }
function regionBucket(rawLocation) { const location = empty(rawLocation); if (/서울|인천|경기/.test(location)) return '수도권'; if (/대전|세종|충남|충북/.test(location)) return '대전·충청권'; return location; }
function normalizeJob(raw) { const hireCodes = splitList(raw.hireTypeLst); const isNew = raw.recrutSe === 'R2010'; const isYouthIntern = hireCodes.some(code => youthInternCodes.includes(code)); return { id: empty(raw.recrutPblntSn), company: empty(raw.instNm), title: empty(raw.recrutPbancTtl), role: '', industry: '', type: isNew ? '신입 정규직' : isYouthIntern ? '인턴' : '', displayType: empty(raw.hireTypeNmLst), location: regionBucket(raw.workRgnNmLst), displayLocation: empty(raw.workRgnNmLst), duties: splitList(raw.ncsCdNmLst), experience: [], major: '', size: '', preferences: empty(raw.prefCondCn) ? [] : [empty(raw.prefCondCn)], deadline: empty(raw.pbancEndYmd), logo: '', color: '#173b72', saved: false, srcUrl: empty(raw.srcUrl), dutyText: empty(raw.ncsCdNmLst), qualification: empty(raw.aplyQlfcCn) }; }
function escapeHtml(value) { return empty(value).replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function getFormFilters() { return { role: $('#roleFilter').value, industry: $('#industryFilter').value, type: $('#typeFilter').value, location: $('#locationFilter').value, duty: $('#dutyFilter').value, experience: $('#experienceFilter').value, major: $('#majorFilter').value, size: $('#sizeFilter').value, preferences: $('#preferenceFilter').checked }; }
function matches(job, filters) { return (!filters.role || job.role === filters.role) && (!filters.industry || job.industry === filters.industry) && (!filters.type || job.type === filters.type) && (!filters.location || job.location === filters.location) && (!filters.duty || job.duties.includes(filters.duty)) && (!filters.experience || job.experience.includes(filters.experience)) && (!filters.major || job.major === filters.major) && (!filters.size || job.size === filters.size) && (!filters.preferences || job.preferences.length > 0); }
function score(job) { let total = 0; if (job.role === '품질관리' && ['화학·소재', '제약·바이오'].includes(job.industry)) total += 3; if (['대전·충청권', '수도권'].includes(job.location) && ['인턴', '신입 정규직'].includes(job.type)) total += 3; if (job.major === '화학·공학 계열' && (job.experience.includes('신입 가능') || job.experience.includes('경력 무관')) && job.duties.some(duty => ['시험·분석', '품질 데이터 관리'].includes(duty))) total += 3; return total; }
function render() { const visible = jobs.filter(job => matches(job, appliedFilters)).sort((a, b) => $('#sortFilter').value === 'deadline' ? a.deadline.localeCompare(b.deadline) : score(b) - score(a) || a.deadline.localeCompare(b.deadline)); $('#resultCount').textContent = visible.length; $('#navCount').textContent = visible.length; $('#savedCount').textContent = jobs.filter(job => job.saved).length; $('#jobGrid').innerHTML = visible.map(job => `<article class="job-card ${score(job) === 9 ? 'recommended' : ''}" data-job-id="${escapeHtml(job.id)}" tabindex="0"><div class="card-top"><div class="company-logo" style="background:${job.color}">${escapeHtml(job.logo)}</div><div class="card-badges">${score(job) === 9 ? '<span class="recommend-badge">추천</span>' : ''}<button class="bookmark ${job.saved ? 'saved' : ''}" data-save-id="${escapeHtml(job.id)}" aria-label="공고 저장">${job.saved ? '♥' : '♡'}</button></div></div><p class="company">${escapeHtml(job.company)}</p><h3>${escapeHtml(job.title)}</h3><div class="card-meta"><span>⌖ ${escapeHtml(job.displayLocation)}</span><span>${escapeHtml(job.displayType)}</span></div><div class="tags">${job.duties.map(duty => `<span class="tag">${escapeHtml(duty)}</span>`).join('')} ${job.preferences.length ? '<span class="tag preference">우대 조건 있음</span>' : ''}</div><div class="card-footer"><span>지원 마감 <strong>${escapeHtml(job.deadline)}</strong></span><span>매칭 <strong>${score(job) * 10 + 5}%</strong></span></div></article>`).join(''); $('#emptyState').hidden = visible.length > 0; const labels = Object.entries(appliedFilters).filter(([, value]) => value).map(([key, value]) => key === 'preferences' ? '우대 조건 있음' : value); $('#activeQuery').innerHTML = labels.length ? `<span>적용 중</span>${labels.map(label => `<b>${escapeHtml(label)}</b>`).join('')}` : ''; $('#activeQuery').hidden = labels.length === 0; document.querySelectorAll('.job-card').forEach(card => { card.addEventListener('click', () => openDetail(card.dataset.jobId)); card.addEventListener('keydown', event => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); openDetail(card.dataset.jobId); } }); }); document.querySelectorAll('[data-save-id]').forEach(button => button.addEventListener('click', event => { event.stopPropagation(); toggleSave(button.dataset.saveId); })); }
function applyFilters() { appliedFilters = getFormFilters(); render(); toast('선택한 조건을 적용했어요.'); }
function resetFilters() { document.querySelectorAll('select').forEach(select => { if (select.id !== 'sortFilter') select.value = ''; }); $('#preferenceFilter').checked = false; appliedFilters = getFormFilters(); render(); toast('필터를 초기화했어요.'); }
function toggleSave(id) { const job = jobs.find(item => item.id === id); if (!job) return; job.saved = !job.saved; render(); toast(job.saved ? '저장한 공고에 추가했어요.' : '저장한 공고에서 삭제했어요.'); if (selectedJob?.id === id) $('#modalSave').textContent = job.saved ? '♥ 저장됨' : '♡ 저장'; }
function openDetail(id) { selectedJob = jobs.find(job => job.id === id); if (!selectedJob) return; $('#modalCompany').textContent = selectedJob.company; $('#modalMatch').textContent = `추천 점수 ${score(selectedJob)}/9`; $('#modalTitle').textContent = selectedJob.title; $('#modalMeta').textContent = [selectedJob.displayLocation, selectedJob.displayType, selectedJob.deadline ? `지원 마감 ${selectedJob.deadline}` : ''].filter(Boolean).join(' · '); $('#modalTags').innerHTML = [selectedJob.industry, selectedJob.size, ...selectedJob.duties].filter(Boolean).map(tag => `<span class="tag">${escapeHtml(tag)}</span>`).join(''); $('#modalDuty').textContent = selectedJob.dutyText; $('#modalQualification').textContent = selectedJob.qualification; $('#modalSave').textContent = selectedJob.saved ? '♥ 저장됨' : '♡ 저장'; $('#detailModal').hidden = false; document.body.classList.add('modal-open'); }
function closeDetail() { $('#detailModal').hidden = true; document.body.classList.remove('modal-open'); selectedJob = null; }
function toast(message) { $('#toast').textContent = message; $('#toast').classList.add('show'); clearTimeout(window.toastTimer); window.toastTimer = setTimeout(() => $('#toast').classList.remove('show'), 1800); }
async function loadJobs() { try { const response = await fetch('/api/jobs', { cache: 'no-store' }); if (!response.ok) throw new Error(`최신 공고를 불러오지 못했습니다. (${response.status})`); const payload = await response.json(); jobs = (Array.isArray(payload) ? payload : payload.jobs || []).map(normalizeJob); render(); } catch (error) { $('#jobGrid').innerHTML = ''; $('#emptyState').hidden = false; $('#emptyState h3').textContent = '최신 공고를 불러오지 못했어요'; $('#emptyState p').textContent = error.message; } }
$('#applyButton').addEventListener('click', applyFilters); $('#resetButton').addEventListener('click', resetFilters); $('#sortFilter').addEventListener('change', render); $('#modalClose').addEventListener('click', closeDetail); $('#detailModal').addEventListener('click', event => { if (event.target.id === 'detailModal') closeDetail(); }); $('#modalSave').addEventListener('click', () => { if (selectedJob) toggleSave(selectedJob.id); }); $('#modalApply').addEventListener('click', () => { if (selectedJob?.srcUrl) window.open(selectedJob.srcUrl, '_blank', 'noopener'); else toast('지원 페이지 URL (모름)'); }); document.addEventListener('keydown', event => { if (event.key === 'Escape' && selectedJob) closeDetail(); });
loadJobs();
